replicaCount: 1

image:
  repository: nicolascifuentesb/airport-k8s
  tag: dae339d
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

container:
  port: 3000

appName: airport-k8s

metrics:
  enabled: true
  port: 3000
  path: /metrics