name: CI-CD GitOps Pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  validate:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./microservices

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test:coverage

      - name: Build project
        run: npm run build

  docker:
    needs: validate

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./microservices

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate Image Tag
        run: |
          echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            -t nicolascifuentesb/airport-k8s:${IMAGE_TAG} \
            -t nicolascifuentesb/airport-k8s:latest .

      - name: Push versioned image
        run: |
          docker push nicolascifuentesb/airport-k8s:${IMAGE_TAG}

      - name: Push latest image
        run: |
          docker push nicolascifuentesb/airport-k8s:latest

  gitops:
    needs: docker

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Image Tag
        run: |
          echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update Helm values
        run: |
          sed -i "s/tag:.*/tag: ${IMAGE_TAG}/" airport-k8s/values.yaml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add airport-k8s/values.yaml

          if git diff --cached --quiet; then
            echo "No changes detected"
            exit 0
          fi

          git commit -m "Update image tag to ${IMAGE_TAG}"
          git push